config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/index'

  get 'pages/about'

  resources :dogs
  resources :owners

  root 'pages#index'

end

app/models/breed.rb
class Breed < ActiveRecord::Base
  has_many :dogs
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :owner
  belongs_to :breed

  has_attached_file :avatar, :styles => {
   :medium => "300x300#",
   :thumb => "100x100#"
   },
  :default_url => "missing_:style.jpg"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates_attachment_size :avatar, :less_than => 3.megabytes,
    :unless => Proc.new {|m| m[:avatar_file_name].blank?}

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :dogs

  def last_first
    "#{last_name}, #{first_name}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /dogs
  # GET /dogs.json
  def index
    @owners = Owner.all
    owner_ids = params[:owner_ids]

    # TODO: Make flash notice dissappear upon a new search.
    if params[:search]
      @dogs = Dog.where("name LIKE '%#{params[:search]}%'")
      if @dogs.size.zero?
        flash.now[:notice] = 'No result found.'
        @dogs = Dog.all
      end
    elsif params[:owner_ids]
      @dogs = Dog.where(owner_id: params[:owner_ids].split(","))
    else
      @dogs = Dog.all
    end
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to dogs_path, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :owner_id, :breed_id, :dob, :vet, :vet_phone, :in_daycare, :avatar)
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:first_name, :last_name, :phone, :emerg_name, :emerg_phone)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br>
    <%= f.collection_select :owner_id, Owner.order('last_name ASC'), :id, :last_first, {prompt: "Select an owner"} %>
  </div>
  <div class="field">
    <%= f.label :breed_id %><br>
    <%= f.collection_select :breed_id, Breed.order('breed ASC'), :id, :breed, {prompt: "Select a breed"} %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="field">
    <%= f.label :vet %><br>
    <%= f.text_field :vet %>
  </div>
  <div class="field">
    <%= f.label :vet_phone %><br>
    <%= f.text_field :vet_phone %>
  </div>
  <div class="field">
    <%= f.label :in_daycare %><br>
    <%= f.check_box :in_daycare %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dogs</h1>

  <div class="row">
    <div class="col-sm-12">
      <p>
        Filter by:
        <% @owners.each do |owner| %>
          <a href="?owner_ids=<%= owner.id %>" class:"filter">
            <button class="btn btn-default btn-xs">
              <%= owner.last_first %>
            </button>
        <% end %>
      </p>
    </div>
  </div>

  <div class="row">
    <% @dogs.each do |dog| %>
    <div class="col-sm-3" >
      <div class="panel panel-default <%= 'panel-success' if dog.in_daycare %>">
        <div class="panel-heading">
          <h3 class="panel-title"><%= dog.name %>, owned by <%= dog.owner.last_first %></h3>
        </div>
        <div class="panel-body">
          <%= dog.breed.breed %>
          <%= image_tag dog.avatar.url(:medium), class: "img-responsive" %>
        </div>
        <div class="panel-footer">
          <!-- In daycare? <%= dog.in_daycare %> -->
          <%= form_for(dog, url: dog_path(dog), :html => {class: "form-inline"}) do |f| %>
            <% if dog.in_daycare %>
              <%= f.hidden_field :in_daycare, :value => false %>
              <%= f.submit "Check Out", class: "btn btn-warning btn-xs" %>
            <% else %>
              <%= f.hidden_field :in_daycare, :value => true %>
              <%= f.submit "Check In", class: "btn btn-success btn-xs" %>
            <% end %>
          <% end %>

          <%= link_to 'Show', dog %>
          <%= link_to 'Edit', edit_dog_path(dog) %>
          <%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
      </div>


    <% end %>
  </div>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @dog.owner.last_first %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @dog.breed.breed %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @dog.dob.stamp("March 1, 1999")  %>
</p>

<p>
  <strong>Vet:</strong>
  <%= @dog.vet %>
</p>

<p>
  <strong>Vet phone:</strong>
  <%= @dog.vet_phone %>
</p>

<p>
  <strong>In daycare:</strong>
  <%= @dog.in_daycare %>
</p>

<p>
 <%= image_tag @dog.avatar.url %>
 <%= image_tag @dog.avatar.url(:medium) %>
 <%= image_tag @dog.avatar.url(:thumb) %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Doggie Place Spa</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/flatly/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Doggie Place Spa", root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Owners", owners_url %></li>
        <li><%= link_to "Dogs", dogs_url %></li>
        <li><a href="#">About</a></li>
      </ul>
      <!-- Add search box to nav bar -->
      <%= form_tag("/dogs", method: "get", role: "search", class: "navbar-form navbar-left") do %>
        <div class="form-group">
          <%= text_field_tag(:search, nil, placeholder: "Search dog name", class: "form-control input_sm") %>
        </div>
        <%= submit_tag("Search", class: "btn btn-default btn-sm") %>
      <% end %>

    <!-- User login -->
    <ul class="nav navbar-nav">
    <% if user_signed_in? %>
      <% current_user.email %>
        <li>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        </li>
    <% else %>
      <li>
        <%= link_to "Sign in", user_session_path %>
      </li>
      <li>
        <%= link_to "Sign up" , user_session_path %>
      </li>
    <% end %>
    </ul>


    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :emerg_name %><br>
    <%= f.text_field :emerg_name %>
  </div>
  <div class="field">
    <%= f.label :emerg_phone %><br>
    <%= f.text_field :emerg_phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Owners</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Emerg name</th>
      <th>Emerg phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.first_name %></td>
        <td><%= owner.last_name %></td>
        <td><%= owner.phone %></td>
        <td><%= owner.emerg_name %></td>
        <td><%= owner.emerg_phone %></td>
        <td><%= link_to content_tag(:i, ":Show", class: "fa fa-eye"), owner %></td>
        <td><%= link_to content_tag(:i, ":Edit", class: "fa fa-pencil"), edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @owner.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @owner.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @owner.phone %>
</p>

<p>
  <strong>Emerg name:</strong>
  <%= @owner.emerg_name %>
</p>

<p>
  <strong>Emerg phone:</strong>
  <%= @owner.emerg_phone %>
</p>

<div class="row">
  <% @owner.dogs.each do |dog| %>
    <div class="col-sm-3" >
      <div class="panel body">
      <%= image_tag dog.avatar.url(:medium), class: "img-responsive" %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'Edit', edit_owner_path(@owner) %>
<%= link_to 'Back', owners_path %>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>